# Generated by Django 4.2.4 on 2026-05-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone',
            new_name='phone',
        ),
    ]
